#########################################################################################################################
#Deployment
#########################################################################################################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myDeployment
  labels:
    tier: myapp
spec:
  replicas: 3
  selector: 
    matchLabels:
      tier: front-end
  template:
    metadata: 
      name: testpod
      labels:
        tier: front-end
    spec:
      containers:
      - name: c00
        image: nginx:latest

  