---
name: Super_Linter
    
on: # yamllint disable-line rule:truthy
    push:
        branches:
            - main 
            - master
    # pull_request: null
    
# permissions: {}
    
jobs:
    Markdown_lint:
        name: Lint
        runs-on: ubuntu-latest
    
        permissions:
          contents: read
          packages: read
          # To report GitHub Actions status checks
          statuses: write
    
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
            with:
              # super-linter needs the full git history to get the
              # list of files that changed across commits
              fetch-depth: 0

          - uses: tj-actions/changed-files@v45
            id: changed-files
            with:
              files: '**/*.md'
              separator: ", "

          - name: List all changed files
            env:
              ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
            run: |
              for file in ${ALL_CHANGED_FILES}; do
                echo "'$file' was changed"
              done

          - name: Markdown_lint
            uses: DavidAnson/markdownlint-cli2-action@v18
            if: steps.changed-files.outputs.any_changed == 'true'
            continue-on-error: false
            with:
              globs: ${{ steps.changed-files.outputs.all_changed_files }}
              fix: true
              
    
          # - name: Super-linter
          #   uses: super-linter/super-linter@v7.2.1 # x-release-please-version
          #   env:
          #     # To report GitHub Actions status checks
          #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}